# List available recipes
default:
    just --list

# Build
build:
    cargo build --release

# Create a image
run root output:
    cargo run --release -- -r {{root}} -o {{output}}

# Clean build artifacts
clean:
    cargo clean

clippy:
    cargo clippy --release
