mode := "release"

# List available recipes
default:
    just --list

# Build binarys
build:
    cargo build --{{mode}} --bins

# Clean build artifacts
clean:
    cargo clean

clippy:
    cargo clippy --{{mode}}
